# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onecorp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: news-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: news-server

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
